/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function exec(argv: string, cwd: string, onLine: (err: null | Error, result: number) => void, onExit: (err: null | Error, result: number) => void): ExecResult
export class ExecResult {
  kill(): void
}
