/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function callThreadsafeFunction(callback: (err: null | Error, result: number) => void): void
export function tmp(): void
export function exec(callback: (err: null | Error, result: number) => void): void
