/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export function callThreadsafeFunction(callback: (err: null | Error, result: number) => void): void
export function tmp(): void
